//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace OfflineSiteMonitoringTool.DataAccessLayer
{
    public partial class tbEPS_Msg
    {
        #region Primitive Properties
    
        public virtual long rid
        {
            get;
            set;
        }
    
        public virtual System.Guid exId
        {
            get;
            set;
        }
    
        public virtual System.DateTime exDatetime
        {
            get;
            set;
        }
    
        public virtual short exMepRoleId
        {
            get;
            set;
        }
    
        public virtual long exMsgSourceEpocRid
        {
            get;
            set;
        }
    
        public virtual long exMsgDestinationEpocRid
        {
            get;
            set;
        }
    
        public virtual long msgCxRid
        {
            get;
            set;
        }
    
        public virtual long msgTypeRid
        {
            get;
            set;
        }
    
        public virtual bool xmlSourceComplete
        {
            get;
            set;
        }
    
        public virtual string xmlSource
        {
            get;
            set;
        }
    
        public virtual Nullable<long> requestMsgRid
        {
            get;
            set;
        }
    
        public virtual Nullable<int> responseSendCount
        {
            get;
            set;
        }
    
        public virtual string schemaVersion
        {
            get;
            set;
        }
    
        public virtual short priorityId
        {
            get;
            set;
        }
    
        public virtual short statusId
        {
            get;
            set;
        }
    
        public virtual string softwareName
        {
            get;
            set;
        }
    
        public virtual string softwareVersion
        {
            get;
            set;
        }
    
        public virtual string softwareAuthor
        {
            get;
            set;
        }
    
        public virtual string appServiceName
        {
            get;
            set;
        }
    
        public virtual decimal appServiceVersion
        {
            get;
            set;
        }
    
        public virtual int sttl
        {
            get;
            set;
        }
    
        public virtual System.Guid id
        {
            get;
            set;
        }
    
        public virtual int stepRef
        {
            get;
            set;
        }
    
        public virtual System.DateTime datetime
        {
            get;
            set;
        }
    
        public virtual short categoryId
        {
            get;
            set;
        }
    
        public virtual Nullable<System.Guid> lastBlockId
        {
            get;
            set;
        }
    
        public virtual int bodyTypeCount
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> batched
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> deletableOn
        {
            get;
            set;
        }
    
        public virtual string msgTxSenderType
        {
            get;
            set;
        }
    
        public virtual string msgTxSenderId
        {
            get;
            set;
        }
    
        public virtual string msgTxSenderName
        {
            get;
            set;
        }
    
        public virtual System.DateTime auditCreatedOn
        {
            get;
            set;
        }
    
        public virtual string auditCreatedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> auditUpdatedOn
        {
            get;
            set;
        }
    
        public virtual string auditUpdatedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> deleteOn
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> deleteOnNextReview
        {
            get;
            set;
        }
    
        public virtual bool deleteOnFixed
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> deleteFailedOn
        {
            get;
            set;
        }

        #endregion
    }
}
