//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace OfflineSiteMonitoringTool.DataAccessLayer
{
    public partial class tbEPS_Organisation
    {
        #region Primitive Properties
    
        public virtual long rid
        {
            get;
            set;
        }
    
        public virtual string id
        {
            get;
            set;
        }
    
        public virtual long organisationTypeRid
        {
            get;
            set;
        }
    
        public virtual string shortName
        {
            get;
            set;
        }
    
        public virtual string name
        {
            get;
            set;
        }
    
        public virtual string healthBoardName
        {
            get;
            set;
        }
    
        public virtual string alternateName
        {
            get;
            set;
        }
    
        public virtual bool prsRefreshEnabled
        {
            get;
            set;
        }
    
        public virtual bool epsServicesEnabled
        {
            get;
            set;
        }
    
        public virtual System.DateTime startDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> endDate
        {
            get;
            set;
        }
    
        public virtual bool archived
        {
            get;
            set;
        }
    
        public virtual System.DateTime auditCreatedOn
        {
            get;
            set;
        }
    
        public virtual string auditCreatedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> auditUpdatedOn
        {
            get;
            set;
        }
    
        public virtual string auditUpdatedBy
        {
            get;
            set;
        }
    
        public virtual string address1
        {
            get;
            set;
        }
    
        public virtual string address2
        {
            get;
            set;
        }
    
        public virtual string address3
        {
            get;
            set;
        }
    
        public virtual string address4
        {
            get;
            set;
        }
    
        public virtual string postCode
        {
            get;
            set;
        }
    
        public virtual string country
        {
            get;
            set;
        }
    
        public virtual string telephone
        {
            get;
            set;
        }
    
        public virtual string fax
        {
            get;
            set;
        }
    
        public virtual string email
        {
            get;
            set;
        }
    
        public virtual string supplier
        {
            get;
            set;
        }
    
        public virtual string supplierReference
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> dispensing
        {
            get;
            set;
        }
    
        public virtual string notes
        {
            get;
            set;
        }

        #endregion
    }
}
