//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace OfflineSiteMonitoringTool.DataAccessLayer
{
    public partial class tbRPT_OrgSupplier
    {
        #region Primitive Properties
    
        public virtual string org
        {
            get;
            set;
        }
    
        public virtual string epoc
        {
            get;
            set;
        }
    
        public virtual string supplier
        {
            get;
            set;
        }
    
        public virtual string product
        {
            get;
            set;
        }
    
        public virtual string version
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> latestMsg
        {
            get;
            set;
        }
    
        public virtual string X509SerialNumber
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> downloaddate
        {
            get;
            set;
        }
    
        public virtual string AuthCertSerialNumber
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> AuthCertDownloadDate
        {
            get;
            set;
        }
    
        public virtual string ipAddress
        {
            get;
            set;
        }
    
        public virtual string reportingSupplier
        {
            get;
            set;
        }
    
        public virtual bool disp
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> extended
        {
            get;
            set;
        }
    
        public virtual string previousSupplier
        {
            get;
            set;
        }
    
        public virtual string previousProduct
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> CmsBetaSite
        {
            get;
            set;
        }
    
        public virtual string EpocCertBy
        {
            get;
            set;
        }
    
        public virtual string ResignCertBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> latestAMS
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> latestCMS
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> latestMAS
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> excludeFromOfflineNotifications
        {
            get;
            set;
        }

        #endregion
    }
}
