//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace OfflineSiteMonitoringTool.DataAccessLayer
{
    public partial class tbRPT_DailyActivityCP
    {
        #region Primitive Properties
    
        public virtual string org
        {
            get;
            set;
        }
    
        public virtual System.DateTime date
        {
            get;
            set;
        }
    
        public virtual string name
        {
            get;
            set;
        }
    
        public virtual Nullable<int> masClaims
        {
            get;
            set;
        }
    
        public virtual Nullable<int> masRegistrations
        {
            get;
            set;
        }
    
        public virtual Nullable<int> masUpdateRequests
        {
            get;
            set;
        }
    
        public virtual Nullable<int> masUpdateResponses
        {
            get;
            set;
        }
    
        public virtual Nullable<int> amsPrescriptionRequests
        {
            get;
            set;
        }
    
        public virtual Nullable<int> amsPResponses
        {
            get;
            set;
        }
    
        public virtual Nullable<int> amsPAResponses
        {
            get;
            set;
        }
    
        public virtual Nullable<int> amsPCResponses
        {
            get;
            set;
        }
    
        public virtual Nullable<int> amsPCAResponses
        {
            get;
            set;
        }
    
        public virtual Nullable<int> amsClaims
        {
            get;
            set;
        }
    
        public virtual Nullable<int> amsCancellations
        {
            get;
            set;
        }
    
        public virtual Nullable<int> cmsRegistrations
        {
            get;
            set;
        }
    
        public virtual Nullable<int> cmsUpdateRequests
        {
            get;
            set;
        }
    
        public virtual Nullable<int> cmsUpdateResponses
        {
            get;
            set;
        }
    
        public virtual Nullable<int> cmsPrescriptionRequests
        {
            get;
            set;
        }
    
        public virtual Nullable<int> cmsPResponses
        {
            get;
            set;
        }
    
        public virtual Nullable<int> cmsPCResponses
        {
            get;
            set;
        }
    
        public virtual Nullable<int> cmsComplianceNotifications
        {
            get;
            set;
        }
    
        public virtual Nullable<int> cmsTreatmentSummaries
        {
            get;
            set;
        }
    
        public virtual Nullable<int> cmsClaims
        {
            get;
            set;
        }
    
        public virtual Nullable<int> cmsCancellations
        {
            get;
            set;
        }

        #endregion
    }
}
