//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace OfflineSiteMonitoringTool.DataAccessLayer
{
    public partial class tbRPT_SupplierContacts
    {
        #region Primitive Properties
    
        public virtual int Rid
        {
            get;
            set;
        }
    
        public virtual string Supplier
        {
            get;
            set;
        }
    
        public virtual string Contact
        {
            get;
            set;
        }

        #endregion
    }
}
