//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace OfflineSiteMonitoringTool.DataAccessLayer
{
    public partial class tbRPT_DailyActivityGP
    {
        #region Primitive Properties
    
        public virtual string org
        {
            get;
            set;
        }
    
        public virtual System.DateTime date
        {
            get;
            set;
        }
    
        public virtual Nullable<int> amsPrescriptions
        {
            get;
            set;
        }
    
        public virtual Nullable<int> amsCancellations
        {
            get;
            set;
        }
    
        public virtual Nullable<int> amsAmendments
        {
            get;
            set;
        }
    
        public virtual Nullable<int> cmsPrescriptions
        {
            get;
            set;
        }
    
        public virtual Nullable<int> cmsCancellations
        {
            get;
            set;
        }
    
        public virtual Nullable<int> cmsUpdatesRequests
        {
            get;
            set;
        }
    
        public virtual Nullable<int> cmsTreatmentUpdates
        {
            get;
            set;
        }
    
        public virtual Nullable<int> cmsComplianceUpdates
        {
            get;
            set;
        }
    
        public virtual Nullable<int> gpRegistrationUpdatesRequests
        {
            get;
            set;
        }

        #endregion
    }
}
